Develop
uncerso/line-paint pull request #1
Opened 2017-11-20 17:21 UTC by uncerso

2017-12-07 15:40 UTC, yurii-litvinov requested changes
- кажется, в ветку попали бинарники и какие-то временные файлы, надо почистить
- при сборке куча предупреждений в духе "LineComponent.cpp(96): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data"
- undo/redo неплохо бы делать неактивными, если операции недоступны

В целом работает, и даже довольно клёво, но надо всё-таки порефакторить, разделив логику работы и интерфейс (чтобы можно было что-то тестировать), и вообще наведя какую-то архитектуру. Это же именно тот самый код, который Вы должны были уметь НЕ писать после этого семестра :)

2017-12-07 15:40 UTC, yurii-litvinov commented on Source/Application.h
> +	MainForm *mainForm;
Оу, паблик-поле?

2017-12-07 15:40 UTC, yurii-litvinov commented on Source/CentralComponent.cpp
> +	//canvas.fillAll(Colour::fromRGB(255, 255, 255));
Закомментированный код в мастере не нужен

2017-12-07 15:40 UTC, yurii-litvinov commented on Source/CentralComponent.cpp
> +}
Этот класс собирается быть God Object-ом, мне кажется. По крайней мере, он уже затащил в себя обработку пользовательского ввода и undo-redo, отрисовку GUI и хранение состояния. Принцип единственности ответственности как-то не очень соблюдается

2017-12-07 15:40 UTC, yurii-litvinov commented on Source/ColourChangeButton.cpp
> +	sendActionMessage("C");         // create
Лучше где-нить объявить константы с этими значениями, чтобы было видно, какого сорта вообще сообщения бывают и случайно не ошибиться в их написании (русская "С" тут может доставить много радости при отладке, например). "Magic string" же.

2017-12-07 15:40 UTC, yurii-litvinov commented on Source/ColourChangeButton.h
> +public:
Не нравится мне такое форматирование

2017-12-07 15:40 UTC, yurii-litvinov commented on Builds/LinuxMakefile/.gdb_history
> +q
Мкей. А Вы уверены, что это надо? :)

2017-12-07 15:40 UTC, yurii-litvinov commented on README.md
> +    drop JUCE folder at the root of drive C
Обычно пути до третьесторонних библиотек задаются через переменные окружения. Иначе те, у кого нет диска C, будут иметь проблемы при сборке. Вообще, кстати, винда не любит, когда кто-то что-то пишет в корень раздела с ОС, нужны админские права.

2017-12-07 15:40 UTC, yurii-litvinov commented on Source/CentralComponent.h
> +	/// Undo
Не очень ценный комментарий

2017-12-07 15:40 UTC, yurii-litvinov commented on Source/CentralComponent.h
> +	void mouseDown(const MouseEvent &event) override;
А зачем они public?

2017-12-07 15:40 UTC, yurii-litvinov commented on Source/LineComponent.h
> +	int getLineThickness();
Они все правда не const-ы?

2017-12-07 15:40 UTC, yurii-litvinov commented on Source/LineComponent.h
> +	enum LineType {
А чего не enum class?

2017-12-07 15:40 UTC, yurii-litvinov commented on Source/ColourChangeButton.h
> +	void selectColour(Colour const &colour);
Надо ещё комментарии к паблик-методам и всё такое

2017-12-07 16:40 UTC, uncerso commented on Source/CentralComponent.cpp
> +	//canvas.fillAll(Colour::fromRGB(255, 255, 255));
Мастер?! Это же девелопт.

2017-12-07 16:41 UTC, yurii-litvinov commented on Source/CentralComponent.cpp
> +	//canvas.fillAll(Colour::fromRGB(255, 255, 255));
Но пуллреквест-то в мастер, если его принять, то случится ужасное

2017-12-07 16:44 UTC, uncerso commented on Source/LineComponent.h
> +	enum LineType {
enum class же не позволяет получать элементы в нём не объявленные. Т.е. a = 1, b = 2 в нём объявлены, а вот a|b сделать уже не получится. Разве не так?

2017-12-07 16:49 UTC, yurii-litvinov commented on Source/LineComponent.h
> +	enum LineType {
Ой, это да, но это не то чтобы хороший способ использовать enum-ы. Лучше для a|b использовать int

2017-12-07 16:54 UTC, uncerso commented on Source/CentralComponent.cpp
> +}
Если проект был бы больше, это бы смахивало на God, но проект жутко мелкий, поэтому решил, чтобы он выполнял некоторую мелкую работу, которую разносить по классам как-то не интересно. (маленький же проект). Конечно, можно замутить KeyMappings или даже ApplicationCommandManager, но зачем, когда в них будет пара строчек?

2017-12-07 16:56 UTC, yurii-litvinov commented on Source/CentralComponent.cpp
> +}
Но надо же не сделать, чтобы работало, а продемонстрировать владение паттернами и основами архитектуры. Но даже для такого проекта, если честно, уже было бы лучше, если бы была более аккуратная декомпозиция

2017-12-07 16:58 UTC, uncerso commented on Source/LineComponent.h
> +	int getLineThickness();
Неправда. Упс.

2017-12-07 17:03 UTC, uncerso commented on Source/CentralComponent.h
> +	void mouseDown(const MouseEvent &event) override;
Забавно, сейчас проверил - действительно private тоже работает. Как-то исторически сложилось, что во всех примерах, что я смотрел по этому поводы, было public. Хм.

2017-12-07 17:07 UTC, uncerso commented
Итого: что таки мне нужно подправить?

2017-12-07 17:09 UTC, yurii-litvinov commented
Все замечания :)

2017-12-07 17:11 UTC, uncerso commented
Серьёзно надо запариться с переменными окружения?

2017-12-07 17:15 UTC, uncerso commented on Source/ColourChangeButton.cpp
> +	sendActionMessage("C");         // create
А точнее? Если бы они использовались не один раз, то была бы константа как переменная. Но тут у меня даже нет идей, куда её вынести-то можно.

2017-12-07 17:15 UTC, yurii-litvinov commented
Это сложно? Если да, то ладно (действительно, если система сборки JUCE не умеет так, то руками править .vcxproj-и то ещё удовольствие). Ну и енамы можно, наверное, не переделывать.

2017-12-07 17:16 UTC, yurii-litvinov commented on Source/ColourChangeButton.cpp
> +	sendActionMessage("C");         // create
А разве она не встречается где-то ещё в if-е? Мне кажется, я её где-то видел :)

Заведите просто .h-ник constants, вынесите туда

2017-12-07 17:17 UTC, uncerso commented
Ну вообще указать, где искать juce это легко. Вот только где его искать?

2017-12-07 17:22 UTC, yurii-litvinov commented
Где-нибудь в $(JUCE_HOME), чтобы можно было написать export JUCE_HOME=~/JUCE && make -j

2017-12-07 20:34 UTC, uncerso commented on Source/ColourChangeButton.cpp
> +	sendActionMessage("C");         // create
Что-то я предчувствую Ваше негодование из-за дефайнов...

2017-12-08 14:07 UTC, uncerso commented
Я же правильно понимаю, что эффект --no-ff при мёрдже веток в мастер из
пуллреквеста даст именно вариант "Squash and merge"?

2017-12-08 16:13 UTC, uncerso commented
https://pastebin.com/QZgCrCQS
1) Какого хрена это вообще работает? (A - privare наследование, а из вне
видно всё. В том числе и protected)
2) Для такого множественного наследования я нашёл решение только через
using. Без них (c public наследованием) отказывается определять нужную
перегрузку. Может знаете решение красивее?

2017-12-08 16:17 UTC, uncerso commented
p.s. работоспособность проверил под gcc и mvs

2017-12-16 13:19 UTC, yurii-litvinov requested changes
Ну да, стало лучше. Теперь можно писать юнит-тесты, наверное.

2017-12-16 13:19 UTC, yurii-litvinov commented on Source/Application.h
> +class MainForm;
Общий для всего проекта неймспейс не хотите? Так обычно принято.

2017-12-16 13:19 UTC, yurii-litvinov commented on Source/CentralComponent.h
> +//#include "LineSettings.h"
Закомментированный код не нужен

2017-12-16 13:19 UTC, yurii-litvinov commented on Source/LineComponent.cpp
> +	, deltaBounds((lineThickness + 1) >> 1, (lineThickness + 1) >> 1 )
Что-то как-то копипаст, может, сделать constructor chaining?

2017-12-16 13:19 UTC, yurii-litvinov commented on Source/Memorize.h
> +class Memorize
Вообще классы обычно называют существительными, а не глаголами

2017-12-16 13:19 UTC, yurii-litvinov commented on Source/stringConstants.h
> +#define REDO "E"
Не, нельзя дефайны, это ж С++

2017-12-16 18:18 UTC, uncerso commented on Source/stringConstants.h
> +#define REDO "E"
А чем Вы предлагаете сделать?

2017-12-17 08:24 UTC, yurii-litvinov commented on Source/stringConstants.h
> +#define REDO "E"
Придумайте что-нибудь

2017-12-26 04:21 UTC, yurii-litvinov requested changes

2017-12-26 04:21 UTC, yurii-litvinov commented on Source/LineSettings.cpp
> +	//deleteAllChildren();
Мм, так это надо делать или не надо?

2017-12-26 04:21 UTC, yurii-litvinov commented on Source/LineSettings.cpp
> +	//double sk = getDesktopScaleFactor();
И это?

2017-12-26 04:21 UTC, yurii-litvinov commented on Source/LineSettings.cpp
> +	//jassert(s.size() == 1);
И вообще закомментированного кода в мастере быть не должно

2017-12-26 04:21 UTC, yurii-litvinov commented on Source/MainForm.h
> +	UnitTestClasses::UnitTestsDemo *unit;
Это как-то не очень юзер-френдли, запускаем приложение, и тут какое-то окно с юнит-тестами

2017-12-26 04:21 UTC, yurii-litvinov commented on Source/UnitTests.hpp
> +struct UnitTestClasses
Юнит-тесты должны быть в отдельном приложении, и чтобы тестируемый код не зависел от тестов даже по сборке. Вы же не хотите поставлять пользователям скомпиленные юнит-тесты в бинарниках, зачем им платить местом на диске и интернет-каналом за то, что только на разработческих машинах нужно?

2017-12-26 04:21 UTC, yurii-litvinov commented on Source/UnitTests.hpp
> +        CustomTestRunner (TestRunnerThread& trt)  : owner (trt)
Внезапно стало модно пробел перед "(" ставить? Во-первых, это неконсистентно, во-вторых, в C++ так скорее не принято. Хотя если Вы пишете на JUCE и там всегда так, то и у Вас должно быть всегда так по идее.

2017-12-26 04:21 UTC, yurii-litvinov commented on Source/stringConstants.h
> +static const char createColourSelector('C');
Но они же не stringConstants, они char constants

2017-12-26 04:21 UTC, yurii-litvinov commented on Source/ColourChangeButton.cpp
> +	sendActionMessage(String((char *)&createColourSelector));         // create
Да ну нафиг. JUCE-овский String не умеет в конструктор из char-а?

2017-12-26 04:21 UTC, yurii-litvinov commented on Source/stringConstants.h
> +/*
А чего все файлы называются с заглавной, а этот со строчной?

2017-12-26 06:39 UTC, uncerso commented on Source/ColourChangeButton.cpp
> +	sendActionMessage(String((char *)&createColourSelector));         // create
Да, я вот тоже афигел. 1000 методов для всего, что душе угодно, а из чара нет.

2017-12-27 04:35 UTC, yurii-litvinov approved these changes
Хорошо, зачтена, но не потому, что мне это нравится, а скорее наоборот, потому что я не хочу больше это смотреть :)

2017-12-27 04:35 UTC, yurii-litvinov commented on Source/Application.cpp
> +namespace line_paint{
Надо пробел перед "{"

2017-12-27 18:18 UTC, uncerso commented
И Вас с наступающим.

2018-02-20 17:19 UTC, merged